import {buildSync} from 'esbuild';
import {gzipSync} from 'zlib';

export function getSizeForEntryPoint(entryPoint) {
  const result = buildSync({
    entryPoints: [entryPoint],
    bundle: true,
    minify: true,
    write: false,
    format: 'esm',
    platform: 'node',
    sourcemap: false,
    minifyWhitespace: true,
    legalComments: 'none',
  });

  if (!result.outputFiles || result.outputFiles.length === 0) {
    throw new Error(`No output generated by esbuild for ${entryPoint}`);
  }

  // Get the bundled file's content (as a Buffer).
  const bundledBuffer = result.outputFiles[0].contents;
  const minified = bundledBuffer.byteLength;

  // Gzip the minified output.
  const gzip = gzipSync(bundledBuffer).byteLength;

  return {minified, gzip};
}
